In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
# 単純なアレイを用意します。
arr1 = np.arange(9).reshape((3,3))

In [4]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# 2つのアレイを列方向（axis=1）に連結します
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [25]:
# 行方向（axis=0）に  []を忘れない
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 =  Series([0,1,2],index=['T','U','V'])
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2 = Series([3,4],index=['X','Y'])
ser2

X    3
Y    4
dtype: int64

In [9]:
# pandas.Seriesでやってみます。
# concatで、デフォルトは axis=0
pd.concat([ser1,ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [10]:
# 列方向に連結すると、DataFrameが出来ます。共通していないところはNaN
pd.concat([ser1,ser2],axis=1) 

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
# 列方向に連結すると、DataFrameが出来ます。共通していないところはNaN  key=引数を使うと列名が指定できる。
pd.concat([ser1,ser2],axis=1,keys=['a', 'b']) 

a    b
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [12]:
# 階層的なindexを付けてSeriesを連結することもできます。
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [13]:
# 列方向に連結すると、列の名前になります。
pd.concat([ser1,ser2],axis=1,keys=['cat1','cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [14]:
# DataFrameでも同じ事ができます。
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

In [15]:
dframe1

X         Y         Z
0  0.896401 -1.282579  0.096846
1  1.031214 -1.144625  0.166587
2  0.313909  0.386671 -1.644320
3  1.637959  1.481137  1.578373

In [16]:
dframe2

Y         Q         X
0  2.503841  0.634372  0.456870
1 -1.181514  0.520726  0.190643
2 -0.632988 -0.807933 -0.544437

In [17]:
# DataFrameを連結します。
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.896401 -1.282579  0.096846
1       NaN  1.031214 -1.144625  0.166587
2       NaN  0.313909  0.386671 -1.644320
3       NaN  1.637959  1.481137  1.578373
0  0.634372  0.456870  2.503841       NaN
1  0.520726  0.190643 -1.181514       NaN
2 -0.807933 -0.544437 -0.632988       NaN

In [18]:
# もとのindexを無視することもできます。
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.896401 -1.282579  0.096846
1       NaN  1.031214 -1.144625  0.166587
2       NaN  0.313909  0.386671 -1.644320
3       NaN  1.637959  1.481137  1.578373
4  0.634372  0.456870  2.503841       NaN
5  0.520726  0.190643 -1.181514       NaN
6 -0.807933 -0.544437 -0.632988       NaN

In [19]:
ser1

T    0
U    1
V    2
dtype: int64

In [20]:
ser2

X    3
Y    4
dtype: int64

In [21]:
# We can specify which specific axes to be used   列方向に結合時だと残したい行名を指定できる。
pd.concat([ser1,ser2],axis=1,join_axes=[['U','V','Y']])

0    1
U  1.0  NaN
V  2.0  NaN
Y  NaN  4.0

# 公式ドキュメントはこちらです。
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'

In [22]:
ser1 =  Series([0,1,2],index=['T','U','V'])
ser1

T    0
U    1
V    2
dtype: int64

In [23]:
ser2 = ser2.reindex(['T','U','V'], fill_value=0)
ser2

T    0
U    0
V    0
dtype: int64

In [24]:
pd.concat([ser1,ser2], axis=0)

T    0
U    1
V    2
T    0
U    0
V    0
dtype: int64