In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
dframe = DataFrame(np.arange(4 * 4).reshape((4, 4)))
# 0,1,2,3をpermutateした（ランダムに並べた）arrayを取得します。
blender = np.random.permutation(4)

blender

array([1, 0, 2, 3])

In [4]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [6]:
# blenderをベースにして、行(axis=0)を入れ替えます（ランダムに） takeメッソドを使うと引数を行番号だと思い、それに従って並べ換える。
dframe.take(blender)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15

In [4]:
# データを採りだして逐一戻す場合を考えてみましょう。 重複復元（ブーストラップサンプル）

In [8]:
# 箱の中に、A,B,C というラベルの付いたビー玉があるとします。
box = np.array(['A','B','C'])
# ランダムにビー玉を取り出す操作を10回やってみましょう。
shaker = np.random.randint(0, len(box), size=10) #0 ~ 2 < len(box)　の　中でsize個分ランダムに取り出す。

In [9]:
shaker

array([2, 2, 0, 2, 0, 2, 0, 0, 0, 1])

In [11]:
# 実際にはこのように使えます。  #boxからshaker（要素番号）に従ってboxの要素を取り出す
hand_grabs = box.take(shaker)
hand_grabs

array(['C', 'C', 'A', 'C', 'A', 'C', 'A', 'A', 'A', 'B'], 
      dtype='<U1')

In [12]:
"""
Numpy を使用した場合の randint は下記の場合だと 0~2
Random を使用した場合の randint は下記の場合だと 0~3
"""
np.random.randint(1, 3, size= (10, 10))

array([[1, 2, 1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 2, 2, 1, 2, 2, 2, 2, 1],
       [1, 1, 1, 2, 1, 2, 2, 2, 1, 2],
       [2, 1, 2, 2, 2, 2, 2, 1, 1, 1],
       [1, 2, 1, 2, 1, 2, 1, 2, 2, 2],
       [1, 2, 1, 1, 2, 2, 1, 2, 2, 1],
       [2, 1, 1, 2, 1, 2, 1, 1, 2, 1],
       [1, 2, 2, 2, 2, 1, 1, 1, 2, 1],
       [1, 2, 2, 1, 1, 1, 2, 2, 1, 2],
       [2, 1, 2, 2, 2, 1, 1, 1, 1, 1]])

In [17]:
import random
random.randint(1, 3)

3

In [18]:
shaker = np.random.randint(0, len(dframe.index), size = 10)

In [19]:
shaker

array([1, 3, 0, 1, 2, 2, 2, 2, 3, 1])

In [21]:
dframe.take(shaker, axis=0)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
2   8   9  10  11
2   8   9  10  11
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7

In [22]:
dframe.take(shaker, axis=1) #axisによる行列指定が可能  axis=1 列番号と思って取り出す

1   3   0   1   2   2   2   2   3   1
0   1   3   0   1   2   2   2   2   3   1
1   5   7   4   5   6   6   6   6   7   5
2   9  11   8   9  10  10  10  10  11   9
3  13  15  12  13  14  14  14  14  15  13

In [23]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15