In [39]:
import numpy as np

from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

X = data.data
y = data.target

In [40]:
data.target_names

array(['malignant', 'benign'],
      dtype='<U9')

In [41]:
from sklearn.model_selection import ShuffleSplit
ss = ShuffleSplit(n_splits=1, 
                  train_size=0.8, 
                  test_size=0.2, 
                  random_state=0)

train_index, test_index = next(ss.split(X, y))

X_train, X_test = X[train_index], X[test_index]
y_train, y_test = y[train_index], y[test_index]

In [42]:
from sklearn import linear_model
clf = linear_model.LogisticRegression()

In [43]:
clf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [44]:
clf.score(X_test, y_test)

0.95614035087719296

In [45]:
y_pred = clf.predict(X_test)

In [46]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


In [47]:
accuracy_score(y_test, y_pred)

0.95614035087719296

In [48]:
cmat = confusion_matrix(y_test, y_pred)
cmat

array([[46,  1],
       [ 4, 63]])

In [49]:
cmat.sum(), cmat.diagonal().sum(), cmat.diagonal().sum() / cmat.sum()

(114, 109, 0.95614035087719296)

In [50]:
TP = cmat[0,0]
TN = cmat[1,1]
FP = cmat[1,0]
FN = cmat[0,1]
TP, TN, FP, FN

(46, 63, 4, 1)

In [51]:
from sklearn.metrics import classification_report

In [52]:
"""
precision : 適合率
recall : 再現率
f1- score : f1 スコア
"""
target_names = data.target_names
print(classification_report(y_test, y_pred, digits=4, target_names=[target_names[0] + ' : 0 ', target_names[1] + ' : 1'])) # digit で小数点第何位まで出力するか決めれる。

                precision    recall  f1-score   support

malignant : 0      0.9200    0.9787    0.9485        47
    benign : 1     0.9844    0.9403    0.9618        67

   avg / total     0.9578    0.9561    0.9563       114



In [53]:
recall_0 = TP / (TP + FN)
# 今、0 をPositiveと考えている
# = 46/(46+1) class 0 recall 再現率，
#             sensitivity 感度,
#             True positive rate (TPR)

recall_0

0.97872340425531912

In [54]:
precision_0 = TP / (TP + FP)
# = 46/(46+4) class 0 precision 適合度，精度

precision_0

0.92000000000000004

In [55]:
# 以下はクラス1の recall と precision
recall_1 = TN / (FP + TN)
# 63 / (63 + 4) class 1 recall, 
#               specificity 特異度     バイナリ分類では、陽性(positive)クラスのリコールは「感度」とも呼ばれます。負(negative)のクラスのリコールは「特異性」である。

specificity = recall_1
recall_1

0.94029850746268662

In [56]:
FP / (FP + TN) 
# False positive rate (FPR) = 1 - specificity

0.059701492537313432

In [57]:
cmat

array([[46,  1],
       [ 4, 63]])

In [58]:
precision_1 = TN / (TN + FN)
# = 63/(63+1) class 1 precision

precision_1

0.984375

In [59]:
f1_0 = 2 * recall_0 * precision_0 / \
       (recall_0 + precision_0)
# = 2 / (1/recall_0 + 1/precision_0) # recallとprecisionの調和平均

f1_0

0.94845360824742264

In [60]:
f1_1 = 2 * recall_1 * precision_1 / \
       (recall_1 + precision_1)
# = 2 / (1/recall_1 + 1/precision_1)

f1_1

0.96183206106870234

#### 調和平均については以下を参照
http://www004.upp.so-net.ne.jp/s_honma/mean/harmony2.htm

In [61]:
from sklearn.metrics import f1_score # f1スコアを計算する関数。 

f1_score(y_test, y_pred, pos_label=0), f1_score(y_test, y_pred, pos_label=1) # pos_labelでどっちクラスのf1スコアを計算するか指定する。

(0.94845360824742264, 0.96183206106870234)

In [62]:
from sklearn.metrics import fbeta_score # fbeta_scoreはf1スコアをより一般的にしたもの。
fbeta_score(y_test, y_pred, beta=1, pos_label=0), fbeta_score(y_test, y_pred, beta=1, pos_label=1) 
# beta=1　とすることによってf1スコアを計算することに等しい

(0.94845360824742264, 0.96183206106870234)

In [63]:
from sklearn.metrics import precision_recall_fscore_support # precision , recall, fscore(beta), support  を一度に計算する関数
precision_recall_fscore_support(y_test, y_pred, beta=1)

(array([ 0.92    ,  0.984375]),
 array([ 0.9787234 ,  0.94029851]),
 array([ 0.94845361,  0.96183206]),
 array([47, 67]))

1 行目は precision, 2 行目は recall, 3 行目は fscore, 4 行目は support

In [64]:
print(classification_report(y_test, y_pred, digits=4, 
                            target_names=[target_names[0] + ' : 0 ', target_names[1] + ' : 1'])) 
# digit で小数点第何位まで出力するか決めれる。

                precision    recall  f1-score   support

malignant : 0      0.9200    0.9787    0.9485        47
    benign : 1     0.9844    0.9403    0.9618        67

   avg / total     0.9578    0.9561    0.9563       114



In [26]:
(precision_0 + precision_1) / 2 # classification_report　の最後の行はただの平均ではない

0.95218749999999996

In [27]:
(precision_0 * 47 + precision_1 * 67) / 114  # classification_report　の最後の行はsupport で重み付けされた平均

0.95783442982456146

10 class problem でも　classfication_report が使える

In [28]:
from sklearn.datasets import load_digits
data = load_digits()

X = data.data
y = data.target

In [29]:
from sklearn.model_selection import ShuffleSplit
ss = ShuffleSplit(n_splits=1, 
                  train_size=0.8, 
                  test_size=0.2,
                  random_state=0)

train_index, test_index = next(ss.split(X, y))

X_train, X_test = X[train_index], X[test_index]
y_train, y_test = y[train_index], y[test_index]

In [30]:
clf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [31]:
clf.score(X_test, y_test)

0.94999999999999996

In [32]:
y_pred = clf.predict(X_test)

In [33]:
accuracy_score(y_test, y_pred)

0.94999999999999996

In [34]:
import pandas as pd

In [35]:
pd.DataFrame(confusion_matrix(y_test, y_pred)) # 混同行列

0   1   2   3   4   5   6   7   8   9
0  27   0   0   0   0   0   0   0   0   0
1   0  31   0   0   0   0   1   0   3   0
2   0   0  34   2   0   0   0   0   0   0
3   0   0   0  29   0   0   0   0   0   0
4   0   0   0   0  30   0   0   0   0   0
5   0   0   0   0   0  39   0   0   0   1
6   0   1   0   0   0   0  43   0   0   0
7   0   1   0   0   1   0   0  37   0   0
8   0   2   1   0   0   0   0   0  35   1
9   0   0   0   1   0   1   0   0   2  37

In [36]:
print(classification_report(y_test, y_pred, digits=4)) # この結果をみて 1と8 の認識率が悪いとよくわかる

             precision    recall  f1-score   support

          0     1.0000    1.0000    1.0000        27
          1     0.8857    0.8857    0.8857        35
          2     0.9714    0.9444    0.9577        36
          3     0.9062    1.0000    0.9508        29
          4     0.9677    1.0000    0.9836        30
          5     0.9750    0.9750    0.9750        40
          6     0.9773    0.9773    0.9773        44
          7     1.0000    0.9487    0.9737        39
          8     0.8750    0.8974    0.8861        39
          9     0.9487    0.9024    0.9250        41

avg / total     0.9509    0.9500    0.9500       360



In [37]:
(0.91* 403 + 0.10 * 47)/ 450

0.8254

In [38]:
1*\
3

3