In [3]:
import numpy as np

In [2]:
# サンプル用のアレイを作る
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
# 転置
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [4]:
# transposeメソッドでも可能
arr.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [11]:
# 引き数をとれる。0は行、1は列
arr.transpose((0,1))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
# 行と列が入れ替わる
arr.transpose((1,0))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [1]:
# swapaxesは、どれとどれを入れ替えるか。
arr.swapaxes(1,0)

NameError: name 'arr' is not defined

In [17]:
arr.swapaxes(0,1)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [19]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
# 行列のかけ算
np.dot(arr.T, arr)
# 45 = 0*0 + 3*3+ 6*6

array([[45, 54, 63],
       [54, 66, 78],
       [63, 78, 93]])

In [4]:
# 3次元行列
arr3d = np.arange(12).reshape((3,2,2))
arr3d

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [5]:
arr3d[0]

array([[0, 1],
       [2, 3]])

In [8]:
# 3次元行列の転置も可能
arr3d.transpose((0,1,2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [7]:
arr3d.T

array([[[ 0,  4,  8],
        [ 2,  6, 10]],

       [[ 1,  5,  9],
        [ 3,  7, 11]]])